### ISSUE TITLE
Galleria's Fatal Error

### ISSUE THREAD

**Issue by mmhan** [kristianmandrup/rails-gallery#5]
After including the gem in the Gemfile and `bundle install` and configuring Galleria, I receive this error for built-in classic theme.

`Fatal error: Theme CSS could not load after 20 sec. Please download the latest theme at http://galleria.io/customer/`

I'm not sure if that's Galleria's error or the gem's error. So, I'll be creating an issue on both repositories, just to be sure.

I'm on `ruby 2.1.0p0`, `rails 4.1.0` & `rails-gallery 0.3.3` it's happening on both localhost and development. The gallery however does work as expected with no problem whatsoever.

**Comment by kristianmandrup** [comment]
As I recall, gems using vendor folder for assets need an update to work with Rails 4.1+. Please check the asset pipeline docs ;)

**Comment by mmhan** [comment]
I'm not sure what you mean by "need an update to work with Rails 4.1+". Gem update?

**Comment by kristianmandrup** [comment]
http://stackoverflow.com/questions/23305570/how-to-effectively-organize-vendor-css-and-js-files-togheter-in-rails-assets

in Rails 4 they have removed vendor folder,so,assets will not server from vendor.

in that `Rails.application.config.assets.paths` not contains `vendor`,if you want you have to add the path in `config/application.rb`

`config.assets.paths << "#{Rails.root}/vendor/assets"`

Since version 4 vendor and lib directories are not included in the asset pipeline by default. If you want to then you should extend assets path or use `app/assets``

So perhaps a better solution is to move/rename `vendor/assets`in rails gallery gem to `app/assets` and see if that works. 

Just fork the repo, link to your fork from your Gemfile then experiment.

**Comment by mmhan** [comment]
Damn, I forgot to reply to your comment after getting this resolved.
